name: "Subscribe to Label"

on:
  pull_request:
    types: ["labeled"]
  issues:
    types: ["labeled"]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: bnjbvr/subscribe-to-label-action@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
